version: "3"
services:
  server:
    container_name: server
    image: node:18.12.1
    command: yarn ts-node-dev src/index.ts
    working_dir: /app
    volumes:
      - ./:/app
    deploy:
      resources:
        limits:
          cpus: "0.5"
